-- ══════════════════════════════════════════════════════════════════
-- ⚠️ DEPRECATED - USE supabase_simple_password_reset.sql INSTEAD
-- ══════════════════════════════════════════════════════════════════
-- This file is kept for reference only.
-- Please use the new simplified version: supabase_simple_password_reset.sql
--
-- The new version has:
-- ✅ Better error handling
-- ✅ Clearer setup instructions  
-- ✅ Explicit pgcrypto extension setup
-- ✅ Updated function name (simple_reset_staff_password)
-- ══════════════════════════════════════════════════════════════════

-- For setup instructions, see: PASSWORD_RESET_SETUP.md
-- For the actual SQL to run, see: supabase_simple_password_reset.sql
